services:
  loki:
    container_name: loki
    image: grafana/loki:3.2.1
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-storage:/loki
    networks:
      - emdr

  promtail:
    container_name: promtail
    image: grafana/promtail:3.2.1
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - /var/lib/docker:/var/lib/docker
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    networks:
      - emdr

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - emdr
    env_file: ./.env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:80'
    networks:
      - emdr

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=:80'
    networks:
      - emdr

  tempo:
    image: grafana/tempo:latest    
    command: [ "-config.file=/etc/tempo.yml" ]
    container_name: tempo
    restart: unless-stopped
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - tempo-storage:/var/tempo
    networks:
      - emdr

  memcached:
    image: memcached:1.6.29-alpine
    restart: unless-stopped
    command:
     - "-p 80"
    container_name: memcached
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Numb

networks:
  emdr:
    external: true

volumes:
  grafana-storage:
    driver: local
  loki-storage:
    driver: local
  prometheus-storage:
    driver: local
  tempo-storage:
    driver: local
