services:
  loki:
    container_name: loki
    image: grafana/loki:3.2.1
    #ports:
    #  - "3100:80"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-storage:/loki
    networks:
      - emdr

  promtail:
    container_name: promtail
    image: grafana/promtail:3.2.1
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - /var/lib/docker:/var/lib/docker
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    networks:
      - emdr

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    #ports:
    #  - "3000:80"
    networks:
      - emdr
    env_file: ./.env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:80'
    networks:
      - emdr

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=:80'
    networks:
      - emdr

networks:
  emdr:
    external: true

volumes:
  grafana-storage:
    driver: local
  loki-storage:
    driver: local
  prometheus-storage:
    driver: local
