deleteDatasources:
  - name: Loki

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki
    basicAuth: false
    isDefault: true
    version: 2
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus
    basicAuth: false
    version: 1
    editable: false
