apiVersion: 1
contactPoints:
    - orgId: 1
      name: Telegram
      receivers:
        - uid: beif9dky70mble
          type: telegram
          settings:
            bottoken: $TELEGRAM_BOT_TOKEN
            chatid: |
              $TELEGRAM_CHANNEL_ID
            disable_notification: false
            disable_web_page_preview: false
            message: '{{ template "telegram_alert" . }}'
            parse_mode: HTML
            protect_content: false
          disableResolveMessage: false

