{
 "title": "API dahsboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_name", "label": "Job name", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  {
   "title": "Healthcheck",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency .95 percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, url) (rate(myemdr_api_request_duration_seconds_bucket{job=\"$job_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(myemdr_api_requests_total{job=\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}