global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter']

  - job_name: 'myemdr-api-dev'
    scrape_interval: 10s
    metrics_path: '/-/metrics'
    static_configs:
      - targets: ['myemdr-api-dev:3334']

  - job_name: 'myemdr-api-staging'
    scrape_interval: 10s
    metrics_path: '/-/metrics'
    static_configs:
      - targets: ['myemdr-api-staging:3334']

  - job_name: 'myemdr-api-production'
    scrape_interval: 10s
    metrics_path: '/-/metrics'
    static_configs:
      - targets: ['myemdr-api-production:3334']
