{
 "title": "API dahsboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "reverse_proxy", "label": "Reverse proxy", "query": { "query": "label_values(up,job)" } },
   { "name": "api_production", "label": "API production", "query": { "query": "label_values(up,job)" } },
   { "name": "api_staging", "label": "API staging", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  {
   "title": "traefik",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$reverse_proxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "myemdr-api [prod]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$api_production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS [prod]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(myemdr_api_requests_total{job=\"$api_production\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "myemdr-api [staging]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$api_staging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS [staging]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(myemdr_api_requests_total{job=\"$api_staging\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Latency .95 percentile [prod]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, url) (rate(myemdr_api_request_duration_seconds_bucket{job=\"$api_production\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency .95 percentile [staging]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, url) (rate(myemdr_api_request_duration_seconds_bucket{job=\"$api_staging\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}